### ISSUE TITLE
Feature request: Add id's to the html

### ISSUE THREAD

**Issue by bernhardh** [dcasia/nova-mega-filter#7]
Could you please add classes or ID's to the html code of the vue component? Something like:

```
<template>
    <card class="flex flex-col p-6" @dblclick.native.self="toggleAllSections" id="nova-mega-filter">
    ....
```

The reason why I am asking: I wanna change the style of it to look like this:

![image](https://user-images.githubusercontent.com/642292/70896605-48f7cc00-1ff1-11ea-9705-745b20ec73f7.png)

![image](https://user-images.githubusercontent.com/642292/70896582-3d0c0a00-1ff1-11ea-85a7-08ed60e7ac68.png)

And this is much easer, when I can write my css vs an exact id or css class like

```css
#nova-mega-filter {
    ....
}
```

and don't have to write hacks like 

```css
[component="index-view"] >div >div >div {
    ....
}
```

**Comment by milewski** [comment]
Agreed!, currently, I have my custom style by overriding the CSS variables provided by nova itself such as:

```
:root {
  --primary: rgb(47, 47, 47);
  --primary-dark: rgb(0, 0, 0);
  --primary-70: rgba(0, 0, 0, 0.7);
  --primary-50: rgba(0, 0, 0, 0.5);
  --primary-30: rgba(0, 0, 0, 0.3);
  --primary-10: rgba(0, 0, 0, 0.1);
  --logo: #000000;
  --sidebar-icon: #fff;
}
```

But it`s okay I will add a unique identifier to the root of this component so you can easily target specific elements

**Comment by bernhardh** [comment]
Thank you. 

Just to make it clear: My point is not the color of the button (this is done by css variables as you suggested). I want to remove the border+background of this specific (and only this) card and add a card like look only for the toggled columns, filters and action sections.

**Comment by bernhardh** [comment]
Basically something like this:

```less
[component="index-view"] >div >div >div >div >div.card {
    background: none !important;
    border: none;
    box-shadow: none;

    [data-old-padding-top] {
        margin-top: 1rem;
        background-color: var(--white);
        -webkit-box-shadow: 0 2px 4px 0 rgba(0,0,0,.05);
        box-shadow: 0 2px 4px 0 rgba(0,0,0,.05);
        border-radius: .5rem;
        padding: 0 1rem 1rem 1rem;
    }
}
```
